version : '3.9'

services:

  redis:
    image: redis
    ports: 
      - '6380:6379'

  db:
    image: postgres:16.1-alpine3.19
    env_file:
      - .env.docker
    volumes:
      - ./backup.sql:/docker-entrypoint-initdb.d/backup.sql
      - pg_data_1:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '5433:5432'

  app:
    build: .
    env_file:
      - .env.docker
    tty: true
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - '8001:8000'
    depends_on:
      db:
        condition: service_healthy
  
  celery:
    build: .
    env_file:
      - .env.docker
    tty: true
    command: celery -A config worker -l INFO
    depends_on:
      - redis
      - app
  
  celery_beat:
    build: .
    env_file:
      - .env.docker
    tty: true
    command: celery -A config beat -l INFO -S django
    depends_on:
      - redis
      - app

volumes:
  pg_data_1:
